
version: 2

sources:
  - name: loreal_bigquerydata
    tables:
      - name: loreal_youtube_data
        description: "Contains facebookads raw data at all resource levels"
        columns:
          - name: advertiser_id
            description: campaign identification
            tests:
              - not_null
              ##- unique
      - name: loreal_product_sig
        description: "Contains googleads raw data at ad resource levels"
      - name: 2020xmxp
        description: "Contains googleads raw data at ad resource levels"